### ISSUE TITLE
`wr` fails when using MSYS2 `git`

### ISSUE THREAD

**Issue by Nahor** [mainmatter/rust-workshop-runner#10]
The MSYS2's version of `git` returns a Unix path (e.g. `/c/some/path/100-exercises-to-learn-rust`), while the Rust API expects a Windows path (e.g. `C:/some/path/100-exercises-to-learn-rust`). So when using `wr` withing a MSys2 environment, it fails to find the exercises:
```
Error: Failed to read the configuration for the current collection of workshop-runner

Caused by:
    0: failed to open file `/c/some/path/100-exercises-to-learn-rust\.wr.toml`
    1: The system cannot find the path specified. (os error 3)
```

One possible fix is to use the [git2 crate](https://crates.io/crates/git2) instead of relying on an external `git` application:
```rust
use git2::Repository;
[...]
pub fn get_git_repository_root_dir() -> Result<PathBuf, anyhow::Error> {
    let repo = Repository::open(".")?;
    repo.workdir().map(|path| path.into()).ok_or(anyhow!(
        "This repository is bare, a worktree is required"
    ))
}
```

But since `wr` doesn't do anything with the git worktree anyway, there is even no need to check that the path is a valid git repo, and just using `"."` works just fine:
```rust
impl ExercisesConfig {
    pub fn load() -> Result<Self, anyhow::Error> {
        let exercises_config_path = PathBuf::from(".").join(".wr.toml");
        [...]
    }
    [...]
}
```

**Comment by LukeMathWalker** [comment]
> But since wr doesn't do anything with the git worktree [...] just using "." works just fine

This is not the case though—`.` won't work if you invoke `wr` from elsewhere in the repository. We do need a reliable way to get the repository root path.
I've solved the issue following [their guidance](https://www.msys2.org/docs/git/#some-tool-i-use-fails-to-work-with-the-git-in-msys2-but-works-fine-with-the-official-one).

**Comment by Nahor** [comment]
Ok but I still think using the `git2` crate would be an even better solution (using `Repository::open_from_env()` instead of the `Repository::open()` suggested earlier, which better emulates the behavior of `git rev-parse` and in particular the search in the parent directories).
