### ISSUE TITLE
Can't run wr after git merge

### ISSUE THREAD

**Issue by ehershey** [mainmatter/rust-workshop-runner#12]
Hi! 
This is a neat tool. I've run into a small problem after merging the latest changes into my local git repo containing [this commit](https://github.com/mainmatter/100-exercises-to-learn-rust/commit/453d8030e5b4c6a43cf91b2f075b28f6c2d37ec2).  I don't remember the exact sequence of events. Perhaps I had most recently opened the exercise `04_traits/05_str_slice` when I did the merge. When I run `wr` now it shows this output and error:
```
       ✅ (04) traits - (02) orphan_rule (Skipped)
        ✅ (04) traits - (03) operator_overloading (Skipped)
        ✅ (04) traits - (04) derive (Skipped)
        ❌ (04) traits - (05) str_slice

        Meditate on your approach and return. Mountains are merely mountains.

error: manifest path `exercises/04_traits/05_str_slice/Cargo.toml` does not exist
```
The `progress.db` sqlite database still includes a reference to the no-longer-present `04_traits/05_str_slice` exercise. 

An easy workaround was to delete the `progress.db` file and run `wr --keep-going` and that worked fine. Maybe if an exercise directory is missing it should be ignored by default? I'm not exactly sure what the ideal behavior would be. Thanks for the tool and course content!

**Comment by vsalova** [comment]
Ah, I ran into the same issue as well! Instead of deleting the entire `progress.db` file, you can also just delete the last entry in the db or the entry where solved is 0 (should be the last exercise that got deleted in the merge):

```
>>> sqlite3 exercises/progress.db
sqlite> select * from open_exercises;
sqlite> PRAGMA table_info(open_exercises);
sqlite> DELETE FROM open_exercises WHERE solved = 0;
sqlite> select * from open_exercises;
``` 

With the last line, just check that the offending exercise is gone. Next time you run `wr`, it should pick up where you left off!
