### ISSUE TITLE
How to change `wr`'s notion of the "current" exercise?

### ISSUE THREAD

**Issue by yossizahn** [mainmatter/rust-workshop-runner#14]
Hi, thanks for the free workshops!
I am working through 100-exercises-to-learn-rust and I keep finding myself wanting to reverse `wr`'s "position" in the workshop, most often this is in order to rerun an exercise that I completed successfully but then thought of a nicer way to solve it.
It would be nice to have a flag to either change the position or to test a specific solution
Thanks

N.B. I know that I can edit progress.db manually, I just think it would be nice to have a command line flag

**Comment by LukeMathWalker** [comment]
You can now use `wr check` from inside an exercise to verify that specific exercise, regardless of where you are in the workshop!
