### ISSUE TITLE
Feature request: auto open file inner code IDE

### ISSUE THREAD

**Issue by bxb100** [mainmatter/rust-workshop-runner#7]
when I type `wr` inner Rustover terminal, I want to open the exercise file automatically

and I have some ideas, I want to do this

**Comment by jaxvanyang** [comment]
Another way is to open the file in any terminal according to the env `EDITOR`.

**Comment by bxb100** [comment]
> Another way is to open the file in any terminal according to the env `EDITOR`.

Currently, when executed in `﻿zed`, ﻿`idea`, ﻿`rustover`, or ﻿`vscode`'s terminal, it will open using IDE or use ﻿`EDITOR` as the fallback.

**Comment by LukeMathWalker** [comment]
Unfortunately, this is not something we want to add to `wr` at the moment—it's difficult to test for regression and likely to be used by a very small percentage of people.
